version: "3.7"
services:

    changelog1:
      image: danilo1337/changelog:latest 
      container_name: changelog1
      ports:
        - '8080:8080'

    changelog2:
      image: danilo1337/changelog:latest 
      container_name: changelog2

    changelog3:
      image: danilo1337/changelog:latest 
      container_name: changelog3

    changelog4:
      image: danilo1337/changelog:latest 
      container_name: changelog4
